'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Automatische My.Settings-Speicherfunktion"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192.168.100.13")>  _
        Public ReadOnly Property smtpServerName() As String
            Get
                Return CType(Me("smtpServerName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("OU=BCW")>  _
        Public ReadOnly Property AdministrationDistinguishedName() As String
            Get
                Return CType(Me("AdministrationDistinguishedName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("OU=Applikationen,OU=Berechtigungen,OU=BCW")>  _
        Public ReadOnly Property GrantsDistinguishedName() As String
            Get
                Return CType(Me("GrantsDistinguishedName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("OU=Rollen,OU=Berechtigungen,OU=BCW")>  _
        Public ReadOnly Property RolesDistinguishedName() As String
            Get
                Return CType(Me("RolesDistinguishedName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("OU=Abteilungsrollen,OU=Rollen,OU=Berechtigungen,OU=BCW")>  _
        Public ReadOnly Property DepartmentRolesDistinguishedName() As String
            Get
                Return CType(Me("DepartmentRolesDistinguishedName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("OU=Applikationsrollen,OU=Rollen,OU=Berechtigungen,OU=BCW")>  _
        Public ReadOnly Property ApplicationRolesDistinguishedName() As String
            Get
                Return CType(Me("ApplicationRolesDistinguishedName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("OU=Basisrollen,OU=Rollen,OU=Berechtigungen,OU=BCW")>  _
        Public ReadOnly Property BaseRolesDistinguishedName() As String
            Get
                Return CType(Me("BaseRolesDistinguishedName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("OU=Extrarollen,OU=Rollen,OU=Berechtigungen,OU=BCW")>  _
        Public ReadOnly Property ExtraRolesDistinguishedName() As String
            Get
                Return CType(Me("ExtraRolesDistinguishedName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("OU=Teamrollen,OU=Rollen,OU=Berechtigungen,OU=BCW")>  _
        Public ReadOnly Property TeamRolesDistinguishedName() As String
            Get
                Return CType(Me("TeamRolesDistinguishedName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("OU=Verweigerungsrollen,OU=Rollen,OU=Berechtigungen,OU=BCW")>  _
        Public ReadOnly Property DenialRolesDistinguishedName() As String
            Get
                Return CType(Me("DenialRolesDistinguishedName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("OU=Urlaubsgruppen,OU=Organisation,OU=BCW")>  _
        Public ReadOnly Property HolidayGroupsDistinguishedName() As String
            Get
                Return CType(Me("HolidayGroupsDistinguishedName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("OU=Arbeitsgruppen,OU=Organisation,OU=BCW")>  _
        Public ReadOnly Property WorkGroupsDistinguishedName() As String
            Get
                Return CType(Me("WorkGroupsDistinguishedName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("OU=Abrechnungsgruppen,OU=Organisation,OU=BCW")>  _
        Public ReadOnly Property AccountingGroupsDistinguishedName() As String
            Get
                Return CType(Me("AccountingGroupsDistinguishedName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("OU=Gruppenmanager,OU=Berechtigungen,OU=BCW")>  _
        Public ReadOnly Property GroupManagersDistinguishedName() As String
            Get
                Return CType(Me("GroupManagersDistinguishedName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("OU=Organisation,OU=BCW")>  _
        Public ReadOnly Property OrganizationGroupsDistinguishedName() As String
            Get
                Return CType(Me("OrganizationGroupsDistinguishedName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CN=Users,DC=bcw-intern,DC=local")>  _
        Public ReadOnly Property UsersContainerDistinguishedName() As String
            Get
                Return CType(Me("UsersContainerDistinguishedName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>Standorte_NORD_Postachspeicher</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Standorte_NRW_Postachsp"& _ 
            "eicher</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>Standorte_SUED_Postachspeicher</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfStr"& _ 
            "ing>")>  _
        Public ReadOnly Property ExchangeDatabaseNames() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("ExchangeDatabaseNames"),Global.System.Collections.Specialized.StringCollection)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://mail.bildungscentrum.de/Powershell?serializationLevel=Full")>  _
        Public ReadOnly Property ExchangePowershellUrl() As String
            Get
                Return CType(Me("ExchangePowershellUrl"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://schemas.microsoft.com/powershell/Microsoft.Exchange")>  _
        Public ReadOnly Property ExchangePowershellSchema() As String
            Get
                Return CType(Me("ExchangePowershellSchema"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("OU=Mappings,OU=Berechtigungen,OU=BCW")>  _
        Public ReadOnly Property MappingsDistinguishedName() As String
            Get
                Return CType(Me("MappingsDistinguishedName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ad.manager@bcw-intern.local")>  _
        Public ReadOnly Property ManipulationUserName() As String
            Get
                Return CType(Me("ManipulationUserName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("38mpztbcfrL3igfM0MMXNTRLPZflASRg")>  _
        Public ReadOnly Property ManipulationUserPassword() As String
            Get
                Return CType(Me("ManipulationUserPassword"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CN=bcw-intern,CN=ypservers,CN=ypServ30,CN=RPcServices,CN=System,dc=bcw-intern,dc="& _ 
            "local")>  _
        Public ReadOnly Property UnixIdDistinguishedName() As String
            Get
                Return CType(Me("UnixIdDistinguishedName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("bcw-gruppe.de")>  _
        Public ReadOnly Property PrimaryMailDomain() As String
            Get
                Return CType(Me("PrimaryMailDomain"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10000")>  _
        Public ReadOnly Property DomainAdminGroupId() As Integer
            Get
                Return CType(Me("DomainAdminGroupId"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10001")>  _
        Public ReadOnly Property DomainUserGroupId() As Integer
            Get
                Return CType(Me("DomainUserGroupId"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LDAP://")>  _
        Public ReadOnly Property LdapProtocolName() As String
            Get
                Return CType(Me("LdapProtocolName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ADSDSOObject")>  _
        Public ReadOnly Property AdoProviderName() As String
            Get
                Return CType(Me("AdoProviderName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public ReadOnly Property StatementConditionsMaximum() As Integer
            Get
                Return CType(Me("StatementConditionsMaximum"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("cn=gruppenmanager.")>  _
        Public ReadOnly Property GroupManagerPrefix() As String
            Get
                Return CType(Me("GroupManagerPrefix"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("(&(objectClass=group)(&(name=gruppenmanager.*)(managedBy=*)))")>  _
        Public ReadOnly Property GroupManagersLdapQueryString() As String
            Get
                Return CType(Me("GroupManagersLdapQueryString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("(&(objectClass=group)(&(!name=gruppenmanager.*)(managedBy=*)))")>  _
        Public ReadOnly Property GroupManagersOfAdminGroupsLdapQueryString() As String
            Get
                Return CType(Me("GroupManagersOfAdminGroupsLdapQueryString"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SSP.ActiveDirectoryX.My.MySettings
            Get
                Return Global.SSP.ActiveDirectoryX.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
